---


- hosts:  webservers
  become: yes
  
  vars:
    root: /var/www/html
    index: index.php
    nginx_path: /etc/nginx/sites-available

  tasks:
    
    - name: Installation of nginx server (latets)
      apt:  
        name: nginx 
        state:  present

    - name: copy nginx default jinja2 template 
      template: 
        src:  default.j2
        dest: "{{ nginx_path }}/default"
    

    - name: Copy the content of website 
      copy: 
        src:   "./{{index}}"
        dest: "{{ root }}/{{ index }}"

    - name: Restart Nginx
      service:
        name: nginx
        state:  restarted

    - name: Install PHP Packages (latest)
      apt:
        update_cache: yes
        name: ['php', 'php-fpm']
        state:  latest 

  

- hosts:  haproxy
  become: yes
  
  vars:
    haproxy_mode: http
    haproxy_algorithm:  roundrobin
    haproxy_backend_servers: backend_servers
    haproxy_path: /etc/haproxy
        
  tasks:
    - name: Install HAProxy (latest)
      apt: 
        name: haproxy 
        state:  present
    
    - name: Copy HAProxy Configuration File 
      template:
        src:  haproxy.cfg.j2
        dest: "{{ haproxy_path }}/haproxy.cfg"
        
    - name: Start HAProxy
      service:  
        name: haproxy
        state:  restarted
    
    - name: Write test function file
      template:
        src:  test.sh.j2
        dest: $HOME/test.sh
    - name: Rudimentary test function
      command:  bash $HOME/test.sh
      register: test
      args:
        warn: no
    - debug:
        msg:  "{{test.stdout}}"
