---


- hosts:  webservers
  become: yes
  
  

  tasks:
    
    - name: Install Nginx Server (latest)
      apt:  
        name: nginx 
        state:  present

    - name: start nginx
      service:
        name: nginx
        state:  started

    - name: copy nginx template 
      copy: 
        src:  templates/default
        dest: /etc/nginx/sites-available/default
    

    - name: Copy the content of static website.
      copy: 
        src:  ./index.php 
        dest: /var/www/html/index.php

    - name: Restart Nginx
      service:
        name: nginx
        state:  restarted

    - name: Install PHP Packages (latest)
      apt:
        update_cache: yes
        name: ['php', 'php-fpm']
        state:  latest 

  

- hosts:  haproxy
  become: yes
  
  vars:
    haproxy_mode: http
    haproxy_algorithm:  roundrobin
    haproxy_backend_servers: backend_servers
        
  tasks:
    - name: Install HAProxy (latest)
      apt: 
        name: haproxy 
        state:  present
    
    - name: Copy HAProxy Configuration File 
      template:
        src:  haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        
    - name: Start HAProxy
      service:  
        name: haproxy
        state:  started
  

    

    





